// <auto-generated />
namespace Dog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _0410 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0410));
        
        string IMigrationMetadata.Id
        {
            get { return "202504100446474_0410"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
